export const FEATURE_PRODUCT_FETCH_REQUEST = "FEATURE_PRODUCT_FETCH_REQUEST"
export const FEATURE_PRODUCT_FETCH_SUCCESS = "FEATURE_PRODUCT_FETCH_SUCCESS"
export const HOT_PRODUCT_FETCH_REQUEST = "HOT_PRODUCT_FETCH_REQUEST"
export const HOT_PRODUCT_FETCH_SUCCESS = "HOT_PRODUCT_FETCH_SUCCESS"
export const SLIDER_FETCH_REQUEST = "SLIDER_FETCH_REQUEST"
export const SLIDER_FETCH_SUCCESS = "SLIDER_FETCH_SUCCESS"
export const CATEGORY_FETCH_REQUEST = "CATEGORY_FETCH_REQUEST"
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS"
export const SET_INFO_PAGINATION_REQUEST = "SET_INFO_PAGINATION_REQUEST"
export const SET_INFO_PAGINATION_SUCCESS = "SET_INFO_PAGINATION_SUCCESS"
export const HANDLE_TASK_REQUEST = "HANDLE_TASK_REQUEST"
export const HANDLE_TASK_SUCCESS = "HANDLE_TASK_SUCCESS"
export const GET_DETAIL_REQUEST = "GET_DETAIL_REQUEST"
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS"
export const ADD_CART = 'ADD_CART'
export const CHANGE_QUANTITY_REQUEST = "CHANGE_QUANTITY_REQUEST"
export const CHANGE_QUANTITY_SUCCESS = "CHANGE_QUANTITY_SUCCESS"
export const UPDATE_CART = "UPDATE_CART"
export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST"
export const GET_ORDER_LIST_REQUEST = "GET_ORDER_LIST_REQUEST"
export const GET_ORDER_LIST_SUCCESS = "GET_ORDER_LIST_SUCCESS"
export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST"
export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
export const ORDER_REQUEST = "ORDER_REQUEST"
export const ORDER_SUCCESS = "ORDER_SUCCESS"
export const SET_USER_DATA = "SET_USER_DATA"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FALSE = "AUTH_FALSE"
export const LOGOUT = "LOGOUT"
export const SET_AUTH_TIMEOUT = "SET_AUTH_TIMEOUT"
export const CHECK_AUTH_BY_TOKEN = "CHECK_AUTH"









// request + success khi fetch or sử lý logic
// success khi update userReducer
// add cart  thay doi moi reducer  ko can request vs success
// thay doi api ->request









